### ISSUE TITLE
should automatically save plots that are displayed

### ISSUE THREAD

**Issue by nirtiac** [Aifred-Health/Vulcan2#28]
The training curve disappears as soon as the script has finished executing.

**Comment by rfratila** [comment]
Since we are already saving the self.record dict, you would be able to just load it and run display_record(model.record) but if you think we should save it, should we just make a folder and save the most recent training curves there?

**Comment by nirtiac** [comment]
Even when I do that it disappears instantly. It’s fixed if I add time.sleep(20) to the end of the script :P

Caitrin

On Oct 9, 2018, at 3:17 PM, Robert Fratila <notifications@github.com<mailto:notifications@github.com>> wrote:


Since we are already saving the self.record dict, you would be able to just load it and run display_record(model.record) but if you think we should save it, should we just make a folder and save the most recent training curves there?

**Comment by rfratila** [comment]
haha I guess that is one way to do it. if you pass it interactive=False does that also do the trick?

**Comment by nirtiac** [comment]
No nothing displays. I see now @priyatharsan had already noted this bug in a comment... we should fix it by calling plt.show() everytime we are done with being interactive - ie on a last epoch or calling while not training.

**Comment by rfratila** [comment]
yeah bc any other plot that we make gets jammed in that instead of making a new window

**Comment by nirtiac** [comment]
plt.clf() usually solves that for me

**Comment by rfratila** [comment]
yeah but that clears the figure no?

**Comment by nirtiac** [comment]
not if you use it after show?

On Oct 9, 2018, at 4:37 PM, Robert Fratila <notifications@github.com<mailto:notifications@github.com>> wrote:


yeah but that clears the figure no?

**Comment by priyatharsan** [comment]
yeah interactive interface of matplotlib is quite buggy. So for now we just let it as it is for now. If you define plt.ioff() at the end of training loop, the plot will stay, so does the training loop too lol. The training will exit only if you exit the plot window. So, we will have to come up with an alternative in future soon. I think we spoke about that to have it replaced with tensorboardX @rfratila ?

**Comment by rfratila** [comment]
Can [this](https://stackoverflow.com/questions/12670101/matplotlib-ion-function-fails-to-be-interactive) `block=True` parameter fix some of the bugginess for now? @priyatharsan

**Comment by priyatharsan** [comment]
I will test that out.

**Comment by joemehltretter** [comment]
Note: This is being done in #46
