### ISSUE TITLE
Plotting on remote server may return error with a different matplotlib backend

### ISSUE THREAD

**Issue by rfratila** [Aifred-Health/Vulcan2#46]
```
if os.name is not "posix":
    if "DISPLAY" not in os.environ:
        matplotlib.use('Agg')
else:
    matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
```

The biggest issue is that if a user forgets the `plot=true` parameter on a device that doesn't have a `DISPLAY` os environment variable, matplotlib will crash. Perhaps if 'plot=true' and there is nowhere to display, raise error quickly to change plot to false?

**Comment by rfratila** [comment]
Specify in the __init__.py where the logger is also configured.

**Comment by joemehltretter** [comment]
@rfratila Plotting currently works for me after I downloaded the xserver

**Comment by rfratila** [comment]
@joemehltretter would you be able to check that plot=True doesn't automatically crash on a server with no $DISPLAY env variable? that's a big worry of mine

**Comment by joemehltretter** [comment]
@rfratila When I remove the display setting from ~/.bashrc it does not crash when `plot=True`. It does run very slow though, I assume because it is attempting to plot each epoch.

**Comment by rfratila** [comment]
yeah it tries to plot which slows it down especially if there's no $DISPLAY var. Should we save the images in some specified folder or return an error if there's no display setting?

**Comment by joemehltretter** [comment]
If we were to save images, would we save for each interval? For the internal data tests I am running 150 epochs and interval of 4 so that would save about 37 graphs. Do you think that is too much saving especially if the users doesn't realize it's being saved and continues to run.

**Comment by rfratila** [comment]
It would overwrite the graph no? I don't think we should be saving without the user knowing. In that case, let's make it crash quickly if plot is left as True when there's no DISPLAY and in the error message recommend to turn on saving. Thoughts @joemehltretter @nirtiac ?

**Comment by joemehltretter** [comment]
I think we could set it up either way, but I would recommend overwriting. I think starting with a crash and error is the best route. If Caitrin agree's I could look into and begin implementing.

**Comment by joemehltretter** [comment]
@rfratila I created and implemented the display variable check in the `remote_server_plotting` branch.

**Comment by rfratila** [comment]
@joemehltretter Looks good but we need a general solution since we also plot in metrics I think?

**Comment by rfratila** [comment]
@joemehltretter I would recommend putting the `if not assert_display_available() and save_path is None:` within the save figure function to simplify the code. If you can do something similar to creating the save_path name so it remakes consistent if a change is made

**Comment by joemehltretter** [comment]
@rfratila I added the check to `save_visualization` function and removed it from the display functions.

**Comment by rfratila** [comment]
@joemehltretter great! Also for save_visualization, shouldn't you also pass it a `plt` reference to know what to save? like `save_visualization(plot, save_path)`?

**Comment by rfratila** [comment]
@joemehltretter feel free to send in a PR for this. it's pretty important

**Comment by joemehltretter** [comment]
@rfratila It saves the proper graphic, I believe because it is stored in global `plt`. It is saving all the proper graphics when fitting two different times. Does that make sense?

**Comment by rfratila** [comment]
yeah that makes sense except im worried that if a new plot comes to the global front and you intended to save the older one it won't

**Comment by joemehltretter** [comment]
@rfratila I added a plot variable so we can avoid that issue. If you can do one more review, then I'll make a PR.
