### ISSUE TITLE
going pure PyTorchic way?

### ISSUE THREAD

**Issue by priyatharsan** [Aifred-Health/Vulcan2#59]
- [ ]  handle dimensions internally as `torch.Size`? 
For example `network.in_dim = [torch.Size([1,28,28]), torch.Size([784])]`

** Feel free to add more bullets we shall discuss here

**Comment by nirtiac** [comment]
this would be on the user facing side? like in `model = ConvNet(
    name='conv_net_test',
    input_network=None,
    dimensions=(1, 28, 28),
    config=conv_net_config,
)
`

**Comment by priyatharsan** [comment]
No no its for internally.

**Comment by priyatharsan** [comment]
Although the network will spit out as `torch.Size`

**Comment by nirtiac** [comment]
hm  would you mind giving an example as to where something would change, cause I can't find a similar usage in the basenetwork or cnn code

**Comment by priyatharsan** [comment]
Take a look at here: https://github.com/Aifred-Health/Vulcan2/blob/update_branch2/vulcanai2/models/basenetwork.py#L86-L93

**Comment by priyatharsan** [comment]
closing this since we decided to stick with `tuple` itself.
