### ISSUE TITLE
SELU Incorrect weight and Bias initialization

### ISSUE THREAD

**Issue by rfratila** [Aifred-Health/Vulcan2#85]
https://github.com/Aifred-Health/Vulcan/blob/master/vulcanai/net.py#L327

ref: https://github.com/AlexiaJM/Deep-learning-with-cats/issues/11

**Comment by rfratila** [comment]
@joemehltretter Did you close the PR?

**Comment by joemehltretter** [comment]
@rfratila No I did not. I got a notification that you closed it and reopened it?

**Comment by rfratila** [comment]
I saw that PR #96 was closed so I thought that it was merged but it says you closed it 2 days ago...

**Comment by rfratila** [comment]
No worries. I reopened it
